vscode:
  extensions:
    - amandeepmittal.expressjs@2.0.0:wGztsS7qUDojy7Is5k8Prg==
    - dbaeumer.vscode-eslint@1.9.1:YVcwmzKVVl+zZ+wMB02GjQ==
    - dariofuzinato.vue-peek@1.0.2:oYJg0oZA/6FBnFfW599HRg==
    - vuetifyjs.vuetify-vscode@0.2.0:NJwDb7TtN4HKH0hc44vIlw==
    - formulahendry.vscode-mysql@0.4.0:ozffYq4AkDKzFalv61HFIw==
    - eamodio.gitlens@10.1.2:H4Ro956WH/qdhYPPEWcaEQ==
    - msjsdiag.debugger-for-chrome@4.12.1:xXSEoy8/LqF/SyOtQTqrQw==
    - octref.vetur@0.22.6:xXCsvthKcTcJhinOkpQTjQ==